name: Reusable Tests

env:
  CARGO_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    ./target/
    
jobs:
  setup-anchor-cli:
    name: Setup Anchor cli
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup/
      - uses: actions/cache@v3
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: ${{ env.CARGO_CACHE_PATH }}
          key: cargo-${{ runner.os }}-debug-anchor-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install --path cli anchor-cli --locked --force --debug
      - run: chmod +x ~/.cargo/bin/anchor
      - uses: actions/upload-artifact@v3
        with:
          name: anchor-binary
          path: ~/.cargo/bin/anchor

      - uses: ./.github/actions/git-diff/
      
